name: MS testing framework

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on:  windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup NuGet
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Nuget restore
      run: nuget restore src/quaternion.sln
      
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: MSBuild
      run: msbuild src/quaternion.sln
      
    - name: Setup VSTest.exe
      uses: Malcolmnixon/Setup-VSTest@v3

    - name: VSTest
      run: vstest.console .\src\x64\Debug\UnitTest.dll
      
# this script is written based on https://github.com/Malcolmnixon/Setup-VSTest under the MIT license.
